name: simple job

on:
  push:
    branches: [ "main" ]
   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: print drployment massage
        run: echo "Deploying website...."

      
